//go:build ignore

// string_locale_tablegen generates the Unicode 17 tables used by the
// locale-sensitive String case mapper. It is intentionally excluded from the
// opfor package; run it explicitly from the repository root with authenticated
// UCD inputs:
//
//	go run ./internal/opfor/string_locale_tablegen.go \
//	  -output internal/opfor/string_locale_unicode_tables.go \
//	  -unicode-data /path/to/UnicodeData.txt \
//	  -prop-list /path/to/PropList.txt
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"slices"
	"strconv"
	"strings"
)

const (
	unicodeDataSHA256 = "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c"
	propListSHA256    = "130dcddcaadaf071008bdfce1e7743e04fdfbc910886f017d9f9ac931d8c64dd"
)

type runeRange struct {
	lo rune
	hi rune
}

func main() {
	unicodeDataPath := flag.String("unicode-data", "", "path to Unicode 17 UnicodeData.txt")
	propListPath := flag.String("prop-list", "", "path to Unicode 17 PropList.txt")
	outputPath := flag.String("output", "internal/opfor/string_locale_unicode_tables.go", "generated Go output")
	check := flag.Bool("check", false, "verify output instead of writing it")
	flag.Parse()
	if *unicodeDataPath == "" || *propListPath == "" {
		panic("-unicode-data and -prop-list are required")
	}

	unicodeData := mustReadPinned(*unicodeDataPath, unicodeDataSHA256)
	propList := mustReadPinned(*propListPath, propListSHA256)
	nonZero, above := parseCombiningClasses(unicodeData)
	softDotted := parseSoftDotted(propList)

	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by string_locale_tablegen.go; DO NOT EDIT.")
	fmt.Fprintln(&output, "// Unicode data version: 17.0.0.")
	fmt.Fprintln(&output, "package opfor")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "const javaStringLocaleUnicodeDataSHA256 = %q\n", unicodeDataSHA256)
	fmt.Fprintf(&output, "const javaStringLocalePropListSHA256 = %q\n", propListSHA256)
	writeRanges(&output, "javaStringCombiningClassNonZeroRanges", nonZero)
	writeRanges(&output, "javaStringCombiningClassAboveRanges", above)
	writeRanges(&output, "javaStringSoftDottedRanges", softDotted)
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		panic(err)
	}
	if *check {
		existing, err := os.ReadFile(*outputPath)
		if err != nil {
			panic(err)
		}
		if !bytes.Equal(existing, formatted) {
			panic(*outputPath + " is stale")
		}
		return
	}
	if err := os.WriteFile(*outputPath, formatted, 0o644); err != nil {
		panic(err)
	}
}

func mustReadPinned(path, want string) []byte {
	data, err := os.ReadFile(path)
	if err != nil {
		panic(err)
	}
	got := fmt.Sprintf("%x", sha256.Sum256(data))
	if got != want {
		panic(fmt.Sprintf("%s SHA-256 = %s, want %s", path, got, want))
	}
	return data
}

func parseCombiningClasses(data []byte) ([]runeRange, []runeRange) {
	var nonZero []rune
	var above []rune
	scanner := bufio.NewScanner(bytes.NewReader(data))
	for scanner.Scan() {
		fields := strings.Split(scanner.Text(), ";")
		if len(fields) < 4 || fields[3] == "0" {
			continue
		}
		codePoint := mustRune(fields[0])
		nonZero = append(nonZero, codePoint)
		if fields[3] == "230" {
			above = append(above, codePoint)
		}
	}
	if err := scanner.Err(); err != nil {
		panic(err)
	}
	return compressRunes(nonZero), compressRunes(above)
}

func parseSoftDotted(data []byte) []runeRange {
	var points []rune
	scanner := bufio.NewScanner(bytes.NewReader(data))
	for scanner.Scan() {
		line := strings.TrimSpace(strings.SplitN(scanner.Text(), "#", 2)[0])
		fields := strings.Split(line, ";")
		if len(fields) != 2 || strings.TrimSpace(fields[1]) != "Soft_Dotted" {
			continue
		}
		bounds := strings.Split(strings.TrimSpace(fields[0]), "..")
		lo := mustRune(bounds[0])
		hi := lo
		if len(bounds) == 2 {
			hi = mustRune(bounds[1])
		}
		for value := lo; value <= hi; value++ {
			points = append(points, value)
		}
	}
	if err := scanner.Err(); err != nil {
		panic(err)
	}
	return compressRunes(points)
}

func mustRune(text string) rune {
	value, err := strconv.ParseInt(strings.TrimSpace(text), 16, 32)
	if err != nil {
		panic(err)
	}
	return rune(value)
}

func compressRunes(points []rune) []runeRange {
	slices.Sort(points)
	points = slices.Compact(points)
	result := make([]runeRange, 0, len(points))
	for _, point := range points {
		if len(result) == 0 || point != result[len(result)-1].hi+1 {
			result = append(result, runeRange{lo: point, hi: point})
			continue
		}
		result[len(result)-1].hi = point
	}
	return result
}

func writeRanges(output *bytes.Buffer, name string, ranges []runeRange) {
	fmt.Fprintf(output, "\nvar %s = []javaRegexRuneRange{\n", name)
	for _, value := range ranges {
		fmt.Fprintf(output, "\t{lo: 0x%x, hi: 0x%x},\n", value.lo, value.hi)
	}
	fmt.Fprintln(output, "}")
}
