package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateFacadePreservesPublicDeclarations(t *testing.T) {
	directory := t.TempDir()
	writeFixture(t, directory, "doc.go", `// Package opfor is the fixture API.
package opfor
`)
	writeFixture(t, directory, "z.go", `package opfor

import (
	ctx "context"
	"io"
	public "example.test/project/source"
)

// Exported is public.
type Exported struct{}
// Generic carries a reader.
type Generic[T io.Reader] struct{ Value T }
// PublicAlias preserves a public-owned identity.
type PublicAlias = public.Diagnostic
type hidden struct{}

// ExportedConst is public.
const ExportedConst = 1
const hiddenConst = 2
// ExportedVar is public.
var ExportedVar = 3
var hiddenVar = 4

// NoResult forwards values.
func NoResult(writer io.Writer, values ...string) {}
func Results(context ctx.Context, value Exported) (Exported, error) { return value, nil }
func GenericFunction[T io.Reader](value T) T { return value }
func (Exported) Method() {}
func hiddenFunction() {}
`)
	generated, err := generateFacade(generatorConfig{
		sourceDirectory: directory, packageName: "opfor",
		implementationImport: "example.test/project/internal/opfor",
	})
	if err != nil {
		t.Fatal(err)
	}
	want := `// Code generated by internal/cmd/apifacade; DO NOT EDIT.

// Package opfor is the fixture API.
package opfor

import (
	ctx "context"
	opforimpl "example.test/project/internal/opfor"
	public "example.test/project/source"
	io "io"
)

// Exported is public.
type Exported = opforimpl.Exported

// Generic carries a reader.
type Generic[T io.Reader] = opforimpl.Generic[T]

// PublicAlias preserves a public-owned identity.
type PublicAlias = public.Diagnostic

const (
	// ExportedConst is public.
	ExportedConst = opforimpl.ExportedConst
)

var (
	// ExportedVar is public.
	ExportedVar = opforimpl.ExportedVar
)

func GenericFunction[T io.Reader](value T) T { return opforimpl.GenericFunction[T](value) }

// NoResult forwards values.
func NoResult(writer io.Writer, values ...string) { opforimpl.NoResult(writer, values...) }

func Results(context ctx.Context, value Exported) (Exported, error) {
	return opforimpl.Results(context, value)
}
`
	if got := string(generated); got != want {
		t.Fatalf("generated facade mismatch\nwant:\n%s\ngot:\n%s", want, got)
	}
	for _, forbidden := range []string{"Method", "hiddenFunction", "hiddenConst", "hiddenVar", "type hidden"} {
		if strings.Contains(string(generated), forbidden) {
			t.Fatalf("generated facade contains %q", forbidden)
		}
	}
	if strings.Contains(string(generated), "var NoResult") || strings.Contains(string(generated), "var Results") {
		t.Fatal("top-level functions were emitted as mutable variables")
	}
}

func TestGenerateFacadeCoalescesDuplicateDeclarations(t *testing.T) {
	directory := t.TempDir()
	writeFixture(t, directory, "platform_a.go", `package opfor

func Platform(value string) string { return value }
type PlatformType struct{}
const PlatformConstant = 1
`)
	writeFixture(t, directory, "platform_b.go", `package opfor

func Platform(value string) string { return value }
type PlatformType int
const PlatformConstant = 2
`)
	generated, err := generateFacade(generatorConfig{
		sourceDirectory: directory, packageName: "opfor",
		implementationImport: "example.test/project/internal/opfor",
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, declaration := range []string{"type PlatformType", "PlatformConstant =", "func Platform("} {
		if got := strings.Count(string(generated), declaration); got != 1 {
			t.Fatalf("%q count = %d, want 1\n%s", declaration, got, generated)
		}
	}
}

func TestGenerateFacadeSkipsBuildIgnoreCommands(t *testing.T) {
	directory := t.TempDir()
	writeFixture(t, directory, "api.go", "package opfor\nfunc Public() {}\n")
	writeFixture(t, directory, "tablegen.go", `//go:build ignore

package main

func MainOnly() {}
`)
	generated, err := generateFacade(generatorConfig{
		sourceDirectory: directory, packageName: "opfor",
		implementationImport: "example.test/project/internal/opfor",
	})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(generated), "func Public") || strings.Contains(string(generated), "MainOnly") {
		t.Fatalf("unexpected generated facade:\n%s", generated)
	}
}

func TestGenerateFacadeRejectsConditionalExports(t *testing.T) {
	directory := t.TempDir()
	writeFixture(t, directory, "api.go", "package opfor\nfunc Public() {}\n")
	writeFixture(t, directory, "platform.go", `//go:build linux

package opfor

func PlatformOnly() {}
`)
	_, err := generateFacade(generatorConfig{
		sourceDirectory: directory, packageName: "opfor",
		implementationImport: "example.test/project/internal/opfor",
	})
	if err == nil || !strings.Contains(err.Error(), "build-constrained export PlatformOnly") {
		t.Fatalf("error = %v, want conditional-export rejection", err)
	}
}

func TestGenerateFacadeRejectsBuildTaggedSignatureMismatch(t *testing.T) {
	directory := t.TempDir()
	writeFixture(t, directory, "platform_a.go", `package opfor
func Platform(value string) string { return value }
`)
	writeFixture(t, directory, "platform_b.go", `package opfor
func Platform(value int) int { return value }
`)
	_, err := generateFacade(generatorConfig{
		sourceDirectory: directory, packageName: "opfor",
		implementationImport: "example.test/project/internal/opfor",
	})
	if err == nil || !strings.Contains(err.Error(), "incompatible signatures") {
		t.Fatalf("error = %v, want incompatible signatures", err)
	}
}

func TestGenerateFacadeRejectsUnexportedImplementationType(t *testing.T) {
	directory := t.TempDir()
	writeFixture(t, directory, "api.go", `package opfor
type privateType struct{}
func Exposed(value privateType) {}
`)
	_, err := generateFacade(generatorConfig{
		sourceDirectory: directory, packageName: "opfor",
		implementationImport: "example.test/project/internal/opfor",
	})
	if err == nil || !strings.Contains(err.Error(), `exposes unexported implementation type "privateType"`) {
		t.Fatalf("error = %v, want unexported-type rejection", err)
	}
}

func TestGenerateFacadeAllowsTypeParameterToShadowPrivateType(t *testing.T) {
	directory := t.TempDir()
	writeFixture(t, directory, "api.go", `package opfor
type value struct{}
func Generic[value any](input value) value { return input }
`)
	generated, err := generateFacade(generatorConfig{
		sourceDirectory: directory, packageName: "opfor",
		implementationImport: "example.test/project/internal/opfor",
	})
	if err != nil {
		t.Fatal(err)
	}
	want := "func Generic[value any](input value) value { return opforimpl.Generic[value](input) }"
	if !strings.Contains(string(generated), want) {
		t.Fatalf("generated facade does not contain %q:\n%s", want, generated)
	}
}

func TestGenerateFacadeIsDeterministicAcrossFileOrder(t *testing.T) {
	directory := t.TempDir()
	writeFixture(t, directory, "z.go", "package opfor\nfunc Zebra() {}\n")
	writeFixture(t, directory, "a.go", "package opfor\nfunc Alpha() {}\n")
	config := generatorConfig{
		sourceDirectory: directory, packageName: "opfor",
		implementationImport: "example.test/project/internal/opfor",
	}
	first, err := generateFacade(config)
	if err != nil {
		t.Fatal(err)
	}
	second, err := generateFacade(config)
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) {
		t.Fatal("successive generator outputs differ")
	}
	if strings.Index(string(first), "func Alpha") > strings.Index(string(first), "func Zebra") {
		t.Fatal("functions are not sorted by name")
	}
}

func writeFixture(t *testing.T, directory, name, source string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(directory, name), []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
}
