// Command apifacade generates the public opfor package facade.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/build/constraint"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

const (
	defaultSourceDirectory      = "internal/opfor"
	defaultOutputPath           = "api.go"
	defaultPackageName          = "opfor"
	defaultImplementationImport = "github.com/sliverarmory/opfor/internal/opfor"
)

type generatorConfig struct {
	sourceDirectory      string
	outputPath           string
	packageName          string
	implementationImport string
}

type sourceFile struct {
	name             string
	file             *ast.File
	imports          map[string]string
	hasDotImport     bool
	buildConstrained bool
}

type typeExport struct {
	name string
	spec *ast.TypeSpec
	file *sourceFile
}

type functionExport struct {
	name string
	decl *ast.FuncDecl
	file *sourceFile
}

type exportSet struct {
	types      []typeExport
	constants  []string
	variables  []string
	functions  []functionExport
	localTypes map[string]struct{}
	allNames   map[string]string
	docs       map[string]string
	packageDoc string
}

type importUse struct {
	path      string
	preferred map[string]struct{}
}

func main() {
	if err := run(os.Args[1:], os.Stdout, os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(arguments []string, stdout, stderr io.Writer) error {
	flags := flag.NewFlagSet("apifacade", flag.ContinueOnError)
	flags.SetOutput(stderr)
	config := generatorConfig{}
	flags.StringVar(&config.sourceDirectory, "source", defaultSourceDirectory, "directory containing the implementation package")
	flags.StringVar(&config.outputPath, "output", defaultOutputPath, "generated facade path, or - for stdout")
	flags.StringVar(&config.packageName, "package", defaultPackageName, "generated package name")
	flags.StringVar(&config.implementationImport, "implementation-import", defaultImplementationImport, "implementation package import path")
	if err := flags.Parse(arguments); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return fmt.Errorf("apifacade: unexpected arguments: %s", strings.Join(flags.Args(), " "))
	}
	generated, err := generateFacade(config)
	if err != nil {
		return err
	}
	if config.outputPath == "-" {
		_, err = stdout.Write(generated)
		return err
	}
	if existing, readErr := os.ReadFile(config.outputPath); readErr == nil && bytes.Equal(existing, generated) {
		return nil
	}
	if err := os.WriteFile(config.outputPath, generated, 0o644); err != nil {
		return fmt.Errorf("apifacade: write %s: %w", config.outputPath, err)
	}
	return nil
}

func generateFacade(config generatorConfig) ([]byte, error) {
	if config.sourceDirectory == "" {
		return nil, errors.New("apifacade: source directory is empty")
	}
	if !token.IsIdentifier(config.packageName) || token.Lookup(config.packageName).IsKeyword() {
		return nil, fmt.Errorf("apifacade: invalid package name %q", config.packageName)
	}
	if config.implementationImport == "" {
		return nil, errors.New("apifacade: implementation import is empty")
	}

	files, fileSet, err := parseProductionFiles(config.sourceDirectory)
	if err != nil {
		return nil, err
	}
	exports, err := collectExports(files, fileSet)
	if err != nil {
		return nil, err
	}
	uses, typeParameterNames, err := discoverImports(exports, fileSet)
	if err != nil {
		return nil, err
	}
	implementationAlias := availableName("opforimpl", typeParameterNames)
	reserved := make(map[string]struct{}, len(exports.allNames)+len(typeParameterNames)+1)
	for name := range exports.allNames {
		reserved[name] = struct{}{}
	}
	for name := range typeParameterNames {
		reserved[name] = struct{}{}
	}
	reserved[implementationAlias] = struct{}{}
	externalAliases := assignImportAliases(uses, reserved)

	typeLines, err := renderTypes(exports.types, exports.docs, implementationAlias, externalAliases, fileSet)
	if err != nil {
		return nil, err
	}
	functionLines, err := renderFunctions(exports.functions, exports.docs, implementationAlias, externalAliases, fileSet)
	if err != nil {
		return nil, err
	}

	var output strings.Builder
	output.WriteString("// Code generated by internal/cmd/apifacade; DO NOT EDIT.\n\n")
	if exports.packageDoc != "" {
		appendDocComment(&output, exports.packageDoc, "")
	}
	output.WriteString("package ")
	output.WriteString(config.packageName)
	output.WriteString("\n\nimport (\n")
	fmt.Fprintf(&output, "\t%s %s\n", implementationAlias, strconv.Quote(config.implementationImport))
	paths := make([]string, 0, len(externalAliases))
	for importPath := range externalAliases {
		paths = append(paths, importPath)
	}
	sort.Strings(paths)
	for _, importPath := range paths {
		fmt.Fprintf(&output, "\t%s %s\n", externalAliases[importPath], strconv.Quote(importPath))
	}
	output.WriteString(")\n")
	appendDeclarationBlock(&output, typeLines)
	appendAliasBlock(&output, "const", exports.constants, exports.docs, implementationAlias)
	appendAliasBlock(&output, "var", exports.variables, exports.docs, implementationAlias)
	appendDeclarationBlock(&output, functionLines)

	formatted, err := format.Source([]byte(output.String()))
	if err != nil {
		return nil, fmt.Errorf("apifacade: format generated facade: %w", err)
	}
	return formatted, nil
}

func parseProductionFiles(directory string) ([]*sourceFile, *token.FileSet, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		return nil, nil, fmt.Errorf("apifacade: read %s: %w", directory, err)
	}
	sort.Slice(entries, func(left, right int) bool { return entries[left].Name() < entries[right].Name() })
	fileSet := token.NewFileSet()
	var files []*sourceFile
	packageName := ""
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		filename := filepath.Join(directory, name)
		sourceBytes, readErr := os.ReadFile(filename)
		if readErr != nil {
			return nil, nil, fmt.Errorf("apifacade: read %s: %w", filename, readErr)
		}
		buildConstrained, buildIgnored, constraintErr := classifyBuildConstraints(sourceBytes)
		if constraintErr != nil {
			return nil, nil, fmt.Errorf("apifacade: %s: %w", filename, constraintErr)
		}
		if buildIgnored {
			continue
		}
		parsed, parseErr := parser.ParseFile(fileSet, filename, sourceBytes, parser.ParseComments|parser.SkipObjectResolution)
		if parseErr != nil {
			return nil, nil, fmt.Errorf("apifacade: parse %s: %w", filename, parseErr)
		}
		if packageName == "" {
			packageName = parsed.Name.Name
		} else if parsed.Name.Name != packageName {
			return nil, nil, fmt.Errorf("apifacade: production files contain packages %q and %q", packageName, parsed.Name.Name)
		}
		source := &sourceFile{
			name: filename, file: parsed, imports: make(map[string]string),
			buildConstrained: buildConstrained,
		}
		for _, importSpec := range parsed.Imports {
			importPath, unquoteErr := strconv.Unquote(importSpec.Path.Value)
			if unquoteErr != nil {
				return nil, nil, fmt.Errorf("apifacade: %s: invalid import path: %w", filename, unquoteErr)
			}
			localName := defaultImportName(importPath)
			if importSpec.Name != nil {
				localName = importSpec.Name.Name
			}
			switch localName {
			case "_":
				continue
			case ".":
				source.hasDotImport = true
				continue
			}
			if previous, exists := source.imports[localName]; exists && previous != importPath {
				return nil, nil, fmt.Errorf("apifacade: %s: import name %q refers to both %q and %q", filename, localName, previous, importPath)
			}
			source.imports[localName] = importPath
		}
		files = append(files, source)
	}
	if len(files) == 0 {
		return nil, nil, fmt.Errorf("apifacade: no production Go files in %s", directory)
	}
	return files, fileSet, nil
}

func classifyBuildConstraints(source []byte) (constrained, ignored bool, resultErr error) {
	var goBuild constraint.Expr
	var plusBuild []constraint.Expr
	for _, lineBytes := range bytes.Split(source, []byte{'\n'}) {
		line := strings.TrimSpace(string(lineBytes))
		if strings.HasPrefix(line, "package ") {
			break
		}
		if !constraint.IsGoBuild(line) && !constraint.IsPlusBuild(line) {
			continue
		}
		expression, err := constraint.Parse(line)
		if err != nil {
			return false, false, fmt.Errorf("parse build constraint %q: %w", line, err)
		}
		constrained = true
		if constraint.IsGoBuild(line) {
			if goBuild != nil {
				return false, false, errors.New("multiple //go:build lines")
			}
			goBuild = expression
		} else {
			plusBuild = append(plusBuild, expression)
		}
	}
	expressions := plusBuild
	if goBuild != nil {
		expressions = []constraint.Expr{goBuild}
	}
	for _, expression := range expressions {
		canBeTrue, _ := constraintPossibleValues(expression, "ignore")
		if !canBeTrue {
			return constrained, true, nil
		}
	}
	return constrained, false, nil
}

// constraintPossibleValues conservatively reports whether expression may be
// true or false when falseTag is fixed to false and every other tag is
// unknown. Correlations between repeated tags are intentionally ignored: that
// can retain an impossible file, but it cannot accidentally discard one.
func constraintPossibleValues(expression constraint.Expr, falseTag string) (canBeTrue, canBeFalse bool) {
	switch typed := expression.(type) {
	case *constraint.TagExpr:
		if typed.Tag == falseTag {
			return false, true
		}
		return true, true
	case *constraint.NotExpr:
		innerTrue, innerFalse := constraintPossibleValues(typed.X, falseTag)
		return innerFalse, innerTrue
	case *constraint.AndExpr:
		leftTrue, leftFalse := constraintPossibleValues(typed.X, falseTag)
		rightTrue, rightFalse := constraintPossibleValues(typed.Y, falseTag)
		return leftTrue && rightTrue, leftFalse || rightFalse
	case *constraint.OrExpr:
		leftTrue, leftFalse := constraintPossibleValues(typed.X, falseTag)
		rightTrue, rightFalse := constraintPossibleValues(typed.Y, falseTag)
		return leftTrue || rightTrue, leftFalse && rightFalse
	default:
		return true, true
	}
}

func defaultImportName(importPath string) string {
	name := path.Base(importPath)
	if len(name) > 1 && name[0] == 'v' {
		allDigits := true
		for _, character := range name[1:] {
			if character < '0' || character > '9' {
				allDigits = false
				break
			}
		}
		if allDigits {
			name = path.Base(path.Dir(importPath))
		}
	}
	return name
}

func collectExports(files []*sourceFile, fileSet *token.FileSet) (exportSet, error) {
	exports := exportSet{
		localTypes: make(map[string]struct{}),
		allNames:   make(map[string]string),
		docs:       make(map[string]string),
	}
	for _, source := range files {
		if filepath.Base(source.name) == "doc.go" && source.file.Doc != nil {
			exports.packageDoc = rawComment(source.file.Doc)
			break
		}
	}
	if exports.packageDoc == "" {
		for _, source := range files {
			if source.file.Doc != nil {
				exports.packageDoc = rawComment(source.file.Doc)
				break
			}
		}
	}
	for _, source := range files {
		for _, declaration := range source.file.Decls {
			switch typed := declaration.(type) {
			case *ast.GenDecl:
				for specificationIndex, specification := range typed.Specs {
					switch spec := specification.(type) {
					case *ast.TypeSpec:
						exports.localTypes[spec.Name.Name] = struct{}{}
						if ast.IsExported(spec.Name.Name) {
							if source.buildConstrained {
								return exportSet{}, conditionalExportError(fileSet.Position(spec.Pos()), spec.Name.Name)
							}
							exports.types = append(exports.types, typeExport{name: spec.Name.Name, spec: spec, file: source})
							recordDoc(exports.docs, "type", spec.Name.Name, declarationDoc(typed, specificationIndex, spec.Doc, spec.Comment))
							if err := recordExportKind(exports.allNames, spec.Name.Name, "type", fileSet.Position(spec.Pos())); err != nil {
								return exportSet{}, err
							}
						}
					case *ast.ValueSpec:
						kind := ""
						target := &exports.variables
						if typed.Tok == token.CONST {
							kind = "const"
							target = &exports.constants
						} else if typed.Tok == token.VAR {
							kind = "var"
						} else {
							continue
						}
						for _, name := range spec.Names {
							if !ast.IsExported(name.Name) {
								continue
							}
							if source.buildConstrained {
								return exportSet{}, conditionalExportError(fileSet.Position(name.Pos()), name.Name)
							}
							*target = append(*target, name.Name)
							recordDoc(exports.docs, kind, name.Name, declarationDoc(typed, specificationIndex, spec.Doc, spec.Comment))
							if err := recordExportKind(exports.allNames, name.Name, kind, fileSet.Position(name.Pos())); err != nil {
								return exportSet{}, err
							}
						}
					}
				}
			case *ast.FuncDecl:
				if typed.Recv == nil && ast.IsExported(typed.Name.Name) {
					if source.buildConstrained {
						return exportSet{}, conditionalExportError(fileSet.Position(typed.Pos()), typed.Name.Name)
					}
					exports.functions = append(exports.functions, functionExport{name: typed.Name.Name, decl: typed, file: source})
					recordDoc(exports.docs, "func", typed.Name.Name, rawComment(typed.Doc))
					if err := recordExportKind(exports.allNames, typed.Name.Name, "func", fileSet.Position(typed.Pos())); err != nil {
						return exportSet{}, err
					}
				}
			}
		}
	}
	sort.Strings(exports.constants)
	exports.constants = compactStrings(exports.constants)
	sort.Strings(exports.variables)
	exports.variables = compactStrings(exports.variables)
	sort.Slice(exports.types, func(left, right int) bool {
		if exports.types[left].name != exports.types[right].name {
			return exports.types[left].name < exports.types[right].name
		}
		return exports.types[left].file.name < exports.types[right].file.name
	})
	sort.Slice(exports.functions, func(left, right int) bool {
		if exports.functions[left].name != exports.functions[right].name {
			return exports.functions[left].name < exports.functions[right].name
		}
		return exports.functions[left].file.name < exports.functions[right].file.name
	})
	return exports, nil
}

func declarationDoc(declaration *ast.GenDecl, specificationIndex int, doc, trailing *ast.CommentGroup) string {
	if doc != nil {
		return rawComment(doc)
	}
	if specificationIndex == 0 && declaration.Doc != nil {
		return rawComment(declaration.Doc)
	}
	return rawComment(trailing)
}

func rawComment(group *ast.CommentGroup) string {
	if group == nil {
		return ""
	}
	comments := make([]string, len(group.List))
	for index, comment := range group.List {
		comments[index] = comment.Text
	}
	return strings.Join(comments, "\n")
}

func recordDoc(docs map[string]string, kind, name, doc string) {
	key := kind + ":" + name
	if docs[key] == "" && doc != "" {
		docs[key] = doc
	}
}

func conditionalExportError(position token.Position, name string) error {
	return fmt.Errorf("apifacade: %s: build-constrained export %s cannot be represented safely in one unconditional api.go", position, name)
}

func recordExportKind(kinds map[string]string, name, kind string, position token.Position) error {
	if previous, exists := kinds[name]; exists && previous != kind {
		return fmt.Errorf("apifacade: %s: exported name %s changes kind across production files (%s and %s)", position, name, previous, kind)
	}
	kinds[name] = kind
	return nil
}

func discoverImports(exports exportSet, fileSet *token.FileSet) (map[string]*importUse, map[string]struct{}, error) {
	uses := make(map[string]*importUse)
	typeParameterNames := make(map[string]struct{})
	for _, exportedType := range exports.types {
		collectTypeParameterNames(exportedType.spec.TypeParams, typeParameterNames)
		declarationTypeParameters := fieldNameSet(exportedType.spec.TypeParams)
		if exportedType.file.hasDotImport && (exportedType.spec.TypeParams != nil || exportedType.spec.Assign.IsValid()) {
			return nil, nil, fmt.Errorf("apifacade: %s: dot imports are unsupported in exported generic declarations", fileSet.Position(exportedType.spec.Pos()))
		}
		if err := analyzeFieldList(exportedType.spec.TypeParams, exportedType.file, exports.localTypes, declarationTypeParameters, uses, fileSet); err != nil {
			return nil, nil, err
		}
		if exportedType.spec.Assign.IsValid() {
			if err := analyzeTypeExpression(exportedType.spec.Type, exportedType.file, exports.localTypes, declarationTypeParameters, uses, fileSet); err != nil {
				return nil, nil, err
			}
		}
	}
	for _, function := range exports.functions {
		collectTypeParameterNames(function.decl.Type.TypeParams, typeParameterNames)
		declarationTypeParameters := fieldNameSet(function.decl.Type.TypeParams)
		if function.file.hasDotImport {
			return nil, nil, fmt.Errorf("apifacade: %s: dot imports are unsupported in exported function signatures", fileSet.Position(function.decl.Pos()))
		}
		for _, fields := range []*ast.FieldList{function.decl.Type.TypeParams, function.decl.Type.Params, function.decl.Type.Results} {
			if err := analyzeFieldList(fields, function.file, exports.localTypes, declarationTypeParameters, uses, fileSet); err != nil {
				return nil, nil, err
			}
		}
	}
	return uses, typeParameterNames, nil
}

func fieldNameSet(fields *ast.FieldList) map[string]struct{} {
	names := make(map[string]struct{})
	if fields == nil {
		return names
	}
	for _, field := range fields.List {
		for _, name := range field.Names {
			names[name.Name] = struct{}{}
		}
	}
	return names
}

func collectTypeParameterNames(fields *ast.FieldList, names map[string]struct{}) {
	if fields == nil {
		return
	}
	for _, field := range fields.List {
		for _, name := range field.Names {
			names[name.Name] = struct{}{}
		}
	}
}

func analyzeFieldList(fields *ast.FieldList, source *sourceFile, localTypes, typeParameters map[string]struct{}, uses map[string]*importUse, fileSet *token.FileSet) error {
	if fields == nil {
		return nil
	}
	for _, field := range fields.List {
		if err := analyzeTypeExpression(field.Type, source, localTypes, typeParameters, uses, fileSet); err != nil {
			return err
		}
	}
	return nil
}

func analyzeTypeExpression(expression ast.Expr, source *sourceFile, localTypes, typeParameters map[string]struct{}, uses map[string]*importUse, fileSet *token.FileSet) error {
	skipped := make(map[*ast.Ident]struct{})
	ast.Inspect(expression, func(node ast.Node) bool {
		switch typed := node.(type) {
		case *ast.Field:
			for _, name := range typed.Names {
				skipped[name] = struct{}{}
			}
		case *ast.SelectorExpr:
			skipped[typed.Sel] = struct{}{}
			if qualifier, ok := typed.X.(*ast.Ident); ok {
				skipped[qualifier] = struct{}{}
			}
		}
		return true
	})
	var analysisErr error
	ast.Inspect(expression, func(node ast.Node) bool {
		if analysisErr != nil {
			return false
		}
		switch typed := node.(type) {
		case *ast.SelectorExpr:
			qualifier, ok := typed.X.(*ast.Ident)
			if !ok {
				analysisErr = fmt.Errorf("apifacade: %s: unsupported qualified type expression", fileSet.Position(typed.Pos()))
				return false
			}
			importPath, exists := source.imports[qualifier.Name]
			if !exists {
				analysisErr = fmt.Errorf("apifacade: %s: unresolved package qualifier %q", fileSet.Position(qualifier.Pos()), qualifier.Name)
				return false
			}
			use := uses[importPath]
			if use == nil {
				use = &importUse{path: importPath, preferred: make(map[string]struct{})}
				uses[importPath] = use
			}
			use.preferred[qualifier.Name] = struct{}{}
			return false
		case *ast.Ident:
			if _, skip := skipped[typed]; skip {
				return false
			}
			if _, typeParameter := typeParameters[typed.Name]; typeParameter {
				return false
			}
			if _, local := localTypes[typed.Name]; local && !ast.IsExported(typed.Name) {
				analysisErr = fmt.Errorf("apifacade: %s: exported API exposes unexported implementation type %q", fileSet.Position(typed.Pos()), typed.Name)
				return false
			}
		}
		return true
	})
	return analysisErr
}

func assignImportAliases(uses map[string]*importUse, reserved map[string]struct{}) map[string]string {
	paths := make([]string, 0, len(uses))
	for importPath := range uses {
		paths = append(paths, importPath)
	}
	sort.Strings(paths)
	aliases := make(map[string]string, len(paths))
	for _, importPath := range paths {
		preferred := make([]string, 0, len(uses[importPath].preferred))
		for name := range uses[importPath].preferred {
			preferred = append(preferred, name)
		}
		sort.Strings(preferred)
		base := "pkg"
		if len(preferred) != 0 {
			base = preferred[0]
		}
		base = sanitizeIdentifier(base)
		alias := availableName(base, reserved)
		aliases[importPath] = alias
		reserved[alias] = struct{}{}
	}
	return aliases
}

func sanitizeIdentifier(name string) string {
	if name == "" {
		return "pkg"
	}
	var result strings.Builder
	for index, character := range name {
		valid := character == '_' || unicode.IsLetter(character) || (index > 0 && unicode.IsDigit(character))
		if valid {
			result.WriteRune(character)
		} else {
			result.WriteRune('_')
		}
	}
	cleaned := result.String()
	if cleaned == "" || !token.IsIdentifier(cleaned) || token.Lookup(cleaned).IsKeyword() {
		return "pkg"
	}
	return cleaned
}

func availableName(base string, reserved map[string]struct{}) string {
	if _, used := reserved[base]; !used && !token.Lookup(base).IsKeyword() {
		return base
	}
	for suffix := 2; ; suffix++ {
		candidate := fmt.Sprintf("%s%d", base, suffix)
		if _, used := reserved[candidate]; !used {
			return candidate
		}
	}
}

func renderTypes(exports []typeExport, docs map[string]string, implementationAlias string, aliases map[string]string, fileSet *token.FileSet) ([]string, error) {
	var lines []string
	for index := 0; index < len(exports); {
		end := index + 1
		for end < len(exports) && exports[end].name == exports[index].name {
			end++
		}
		var rendered string
		for _, candidate := range exports[index:end] {
			declaration, err := renderType(candidate, implementationAlias, aliases, fileSet)
			if err != nil {
				return nil, err
			}
			if rendered == "" {
				rendered = declaration
			} else if rendered != declaration {
				return nil, fmt.Errorf("apifacade: exported type %s has incompatible generic declarations across build-tag files", candidate.name)
			}
		}
		lines = append(lines, withDoc(docs["type:"+exports[index].name], rendered))
		index = end
	}
	return lines, nil
}

func renderType(exported typeExport, implementationAlias string, aliases map[string]string, fileSet *token.FileSet) (string, error) {
	declaration, arguments, err := renderTypeParameters(exported.spec.TypeParams, exported.file, aliases, fileSet)
	if err != nil {
		return "", err
	}
	if exported.spec.Assign.IsValid() {
		target, renderErr := renderExpression(exported.spec.Type, exported.file, aliases, fileSet)
		if renderErr != nil {
			return "", renderErr
		}
		return fmt.Sprintf("type %s%s = %s", exported.name, declaration, target), nil
	}
	return fmt.Sprintf("type %s%s = %s.%s%s", exported.name, declaration, implementationAlias, exported.name, arguments), nil
}

func renderFunctions(exports []functionExport, docs map[string]string, implementationAlias string, aliases map[string]string, fileSet *token.FileSet) ([]string, error) {
	var lines []string
	for index := 0; index < len(exports); {
		end := index + 1
		for end < len(exports) && exports[end].name == exports[index].name {
			end++
		}
		var rendered string
		for _, candidate := range exports[index:end] {
			declaration, err := renderFunction(candidate, implementationAlias, aliases, fileSet)
			if err != nil {
				return nil, err
			}
			if rendered == "" {
				rendered = declaration
			} else if rendered != declaration {
				return nil, fmt.Errorf("apifacade: exported function %s has incompatible signatures across build-tag files", candidate.name)
			}
		}
		lines = append(lines, withDoc(docs["func:"+exports[index].name], rendered))
		index = end
	}
	return lines, nil
}

func renderFunction(exported functionExport, implementationAlias string, aliases map[string]string, fileSet *token.FileSet) (string, error) {
	typeParameters, typeArguments, err := renderTypeParameters(exported.decl.Type.TypeParams, exported.file, aliases, fileSet)
	if err != nil {
		return "", err
	}
	parameters, callArguments, err := renderParameters(exported.decl.Type.Params, exported.file, aliases, implementationAlias, fileSet)
	if err != nil {
		return "", err
	}
	results, resultCount, err := renderResults(exported.decl.Type.Results, exported.file, aliases, implementationAlias, fileSet)
	if err != nil {
		return "", err
	}
	call := fmt.Sprintf("%s.%s%s(%s)", implementationAlias, exported.name, typeArguments, strings.Join(callArguments, ", "))
	body := call
	if resultCount != 0 {
		body = "return " + call
	}
	return fmt.Sprintf("func %s%s(%s)%s { %s }", exported.name, typeParameters, strings.Join(parameters, ", "), results, body), nil
}

func renderTypeParameters(fields *ast.FieldList, source *sourceFile, aliases map[string]string, fileSet *token.FileSet) (string, string, error) {
	if fields == nil || len(fields.List) == 0 {
		return "", "", nil
	}
	var declarations []string
	var arguments []string
	for _, field := range fields.List {
		if len(field.Names) == 0 {
			return "", "", fmt.Errorf("apifacade: %s: unnamed type parameter", fileSet.Position(field.Pos()))
		}
		constraint, err := renderExpression(field.Type, source, aliases, fileSet)
		if err != nil {
			return "", "", err
		}
		names := make([]string, len(field.Names))
		for index, name := range field.Names {
			names[index] = name.Name
			arguments = append(arguments, name.Name)
		}
		declarations = append(declarations, strings.Join(names, ", ")+" "+constraint)
	}
	return "[" + strings.Join(declarations, ", ") + "]", "[" + strings.Join(arguments, ", ") + "]", nil
}

func renderParameters(fields *ast.FieldList, source *sourceFile, aliases map[string]string, implementationAlias string, fileSet *token.FileSet) ([]string, []string, error) {
	if fields == nil {
		return nil, nil, nil
	}
	var declarations []string
	var arguments []string
	reserved := make(map[string]struct{})
	for _, field := range fields.List {
		for _, name := range field.Names {
			if name.Name != "_" {
				reserved[name.Name] = struct{}{}
			}
		}
	}
	argumentIndex := 0
	for _, field := range fields.List {
		typeText, err := renderExpression(field.Type, source, aliases, fileSet)
		if err != nil {
			return nil, nil, err
		}
		count := len(field.Names)
		if count == 0 {
			count = 1
		}
		_, variadic := field.Type.(*ast.Ellipsis)
		for fieldIndex := 0; fieldIndex < count; fieldIndex++ {
			name := ""
			if len(field.Names) != 0 {
				name = field.Names[fieldIndex].Name
			}
			if name == "" || name == "_" || name == implementationAlias {
				for {
					name = fmt.Sprintf("_arg%d", argumentIndex)
					argumentIndex++
					if _, exists := reserved[name]; !exists && name != implementationAlias {
						break
					}
				}
			}
			reserved[name] = struct{}{}
			declarations = append(declarations, name+" "+typeText)
			argument := name
			if variadic {
				argument += "..."
			}
			arguments = append(arguments, argument)
		}
	}
	return declarations, arguments, nil
}

func renderResults(fields *ast.FieldList, source *sourceFile, aliases map[string]string, implementationAlias string, fileSet *token.FileSet) (string, int, error) {
	if fields == nil || len(fields.List) == 0 {
		return "", 0, nil
	}
	var results []string
	for _, field := range fields.List {
		typeText, err := renderExpression(field.Type, source, aliases, fileSet)
		if err != nil {
			return "", 0, err
		}
		count := len(field.Names)
		if count == 0 {
			count = 1
		}
		for index := 0; index < count; index++ {
			if len(field.Names) == 0 {
				results = append(results, typeText)
				continue
			}
			name := field.Names[index].Name
			if name == implementationAlias {
				results = append(results, typeText)
				continue
			}
			results = append(results, name+" "+typeText)
		}
	}
	return " (" + strings.Join(results, ", ") + ")", len(results), nil
}

func renderExpression(expression ast.Expr, source *sourceFile, aliases map[string]string, fileSet *token.FileSet) (string, error) {
	ast.Inspect(expression, func(node ast.Node) bool {
		selector, ok := node.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		qualifier, ok := selector.X.(*ast.Ident)
		if !ok {
			return true
		}
		if importPath, exists := source.imports[qualifier.Name]; exists {
			qualifier.Name = aliases[importPath]
		}
		return false
	})
	var output bytes.Buffer
	if err := format.Node(&output, fileSet, expression); err != nil {
		return "", fmt.Errorf("apifacade: %s: render type expression: %w", fileSet.Position(expression.Pos()), err)
	}
	return output.String(), nil
}

func appendDeclarationBlock(output *strings.Builder, declarations []string) {
	if len(declarations) == 0 {
		return
	}
	output.WriteString("\n")
	for index, declaration := range declarations {
		if index != 0 {
			output.WriteString("\n\n")
		}
		output.WriteString(declaration)
		output.WriteString("\n")
	}
}

func appendAliasBlock(output *strings.Builder, keyword string, names []string, docs map[string]string, implementationAlias string) {
	if len(names) == 0 {
		return
	}
	output.WriteString("\n")
	output.WriteString(keyword)
	output.WriteString(" (\n")
	for _, name := range names {
		appendDocComment(output, docs[keyword+":"+name], "\t")
		fmt.Fprintf(output, "\t%s = %s.%s\n", name, implementationAlias, name)
	}
	output.WriteString(")\n")
}

func withDoc(doc, declaration string) string {
	if doc == "" {
		return declaration
	}
	return doc + "\n" + declaration
}

func appendDocComment(output *strings.Builder, doc, indent string) {
	if doc == "" {
		return
	}
	for _, line := range strings.Split(doc, "\n") {
		output.WriteString(indent)
		output.WriteString(line)
		output.WriteString("\n")
	}
}

func compactStrings(values []string) []string {
	if len(values) < 2 {
		return values
	}
	write := 1
	for read := 1; read < len(values); read++ {
		if values[read] == values[write-1] {
			continue
		}
		values[write] = values[read]
		write++
	}
	return values[:write]
}
